version: '3'

services:
  influx:
    image: influxdb
    depends_on:
     - cadvisor
    volumes:
      - influx:/var/lib/influxdb
    networks:
     - monitor
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  grafana:
    image: grafana/grafana
    depends_on:
     - cadvisor
     - influxdb
    networks:
     - monitor
     - traefik_traefik-net
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - influx
    deploy:
      replicas: 1
      labels:
      - "traefik.port=3000"
      - "traefik.docker.network=traefik_traefik-net"
      - "traefik.frontend.rule=Host:grafana.example.com"
      placement:
        constraints:
          - node.role == manager

  cadvisor:
    image: google/cadvisor
    hostname: '{{.Node.ID}}'
    command: -logtostderr -docker_only -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influx:8086
    networks:
     - monitor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - influx
    deploy:
      mode: global

volumes:
  influx:
    driver: convoy
  grafana:
    driver: convoy
networks:
  traefik_traefik-net:
    external: true
  monitor:
     driver: overlay
     ipam:
      config:
      - subnet: 172.31.0.0/24